services:
  - type: web
    name: flexflow-api
    runtime: node
    rootDir: apps/api
    buildCommand: apt-get install -y openssl libssl-dev && corepack enable pnpm && pnpm install --no-frozen-lockfile && pnpm prisma generate
    startCommand: apt-get install -y openssl libssl-dev && pnpm prisma migrate deploy && node src/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 4000
      - key: DATABASE_URL
        sync: false
      - key: JWT_ACCESS_SECRET
        sync: false
      - key: JWT_REFRESH_SECRET
        sync: false
      - key: CLIENT_ORIGIN
        sync: false
      - key: RESEND_API_KEY
        sync: false
